backend:
  name: github
  repo: HA24030014533/Econlytix # User's repo
  branch: main
  auth_type: implicit # Or 'pkce' if your chosen handler explicitly supports and recommends it
  base_url: https://econlytix.vercel.app # User's Vercel deployment domain
  auth_endpoint: /api/auth # Or the actual path to your new auth initiation function

# Update local backend configuration
# local_backend:
#   url: 'http://localhost:3000/api/cms'

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/posts
    label: "Blog Posts" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - label: "Categories"
        name: "categories"
        widget: "select"
        multiple: true
        options: ["Politics", "Economy", "Tech", "Crypto", "Markets", "Policy"]
        required: false
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Summary", name: "summary", widget: "text", required: false}
      - {label: "Hero Bullet Point", name: "hero_bullet", widget: "string", required: false, hint: "Bullet point for hero position (optional)"}
      - label: "Post Display Settings"
        name: "display_settings"
        widget: "object"
        fields:
          - {label: "Display Area", name: "display_area", widget: "select", 
             options: [
               "Default",
               "Homepage Hero",
               "Homepage Featured",
               "Homepage Grid",
               "Homepage List",
               "Sidebar Featured",
               "Sidebar Recent",
               "Category Hero",
               "Category Featured",
               "Archive Hero",
               "Archive Featured"
             ], 
             default: "Default", 
             required: false,
             hint: "Controls where and how the post appears on the site"}
          - {label: "Layout Style", name: "layout_style", widget: "select",
             options: [
               "Standard",
               "Full-Width",
               "Compact",
               "Card",
               "Featured Large",
               "Hero Left",
               "Hero Center",
               "Hero Right",
               "Opinion Style",
               "Grid Item"
             ],
             default: "Standard",
             required: false,
             hint: "Controls the visual presentation of the post"}
          - {label: "Column Priority", name: "column_priority", widget: "select",
             options: [
               "Standard",
               "Full-Width",
               "Highlight Left",
               "Highlight Right",
               "Sticky",
               "Prominent"
             ],
             default: "Standard",
             required: false,
             hint: "Controls the post's position and emphasis in grid layouts"}
          - {label: "Display Order", name: "display_order", widget: "number",
             value_type: "int",
             required: false,
             hint: "Lower numbers appear first (optional)"}
          - {label: "Featured Until", name: "featured_until", widget: "datetime",
             required: false,
             hint: "Post will be featured until this date (optional)"}
          - {label: "Hide from Lists", name: "hide_from_lists", widget: "boolean",
             default: false,
             required: false,
             hint: "Hide this post from category and archive listings"}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      # Add other specific pages here if needed, e.g., elements.md
      # - file: "content/elements.md"
      #   label: "Elements Page"
      #   name: "elements"
      #   fields:
      #     - {label: "Title", name: "title", widget: "string"}
      #     - {label: "Body", name: "body", widget: "markdown"}
  - name: "config"
    label: "Site Configuration"
    files:
      - file: "config/config.json"
        label: "Main Configuration"
        name: "main_config"
        fields:
          - label: "Site Details"
            name: "site"
            widget: "object"
            fields:
              - {label: "Site Title", name: "title", widget: "string"}
              - {label: "Base URL", name: "base_url", widget: "string"}
              - {label: "Favicon", name: "favicon", widget: "image", media_folder: "public/images", public_folder: "/images"}
              - {label: "Logo", name: "logo", widget: "image", media_folder: "public/images", public_folder: "/images"}
              - {label: "Logo White", name: "logo_white", widget: "image", media_folder: "public/images", public_folder: "/images"}
              - {label: "Logo Width", name: "logo_width", widget: "string"}
              - {label: "Logo Height", name: "logo_height", widget: "string"}
              - {label: "Logo Text", name: "logo_text", widget: "string"}
          - label: "Settings"
            name: "settings"
            widget: "object"
            fields:
              - {label: "Enable Theme Switcher", name: "theme_switcher", widget: "boolean", default: true}
              - {label: "Default Theme", name: "default_theme", widget: "select", options: ["system", "light", "dark"]}
              - {label: "Pagination", name: "pagination", widget: "number", value_type: "int"}
              - label: "Inner Pagination Options"
                name: "InnerPaginationOptions"
                widget: "object"
                fields:
                  - {label: "Enable Top Pagination", name: "enableTop", widget: "boolean", default: false}
                  - {label: "Enable Bottom Pagination", name: "enableBottom", widget: "boolean", default: true}
              - {label: "Summary Length", name: "summary_length", widget: "number", value_type: "int"}
              - {label: "Blog Folder", name: "blog_folder", widget: "string", default: "posts"}
          - label: "Metadata"
            name: "metadata"
            widget: "object"
            fields:
              - {label: "Meta Author", name: "meta_author", widget: "string"}
              - {label: "Meta Image", name: "meta_image", widget: "image", media_folder: "public/images", public_folder: "/images"}
              - {label: "Meta Description", name: "meta_description", widget: "text"}
          - label: "Widgets"
            name: "widgets"
            widget: "object"
            fields:
              - label: "About Widget"
                name: "about"
                widget: "object"
                fields:
                  - {label: "Enable", name: "enable", widget: "boolean", default: true}
                  - {label: "Content", name: "content", widget: "text"}
              - label: "Featured Posts Widget"
                name: "featured_posts"
                widget: "object"
                fields:
                  - {label: "Enable", name: "enable", widget: "boolean", default: true}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Number of Posts to Show", name: "showPost", widget: "number", value_type: "int"}
              - label: "Categories Widget"
                name: "categories"
                widget: "object"
                fields:
                  - {label: "Enable", name: "enable", widget: "boolean", default: true}
                  - {label: "Title", name: "title", widget: "string"}
              - label: "Newsletter Widget"
                name: "newsletter"
                widget: "object"
                fields:
                  - {label: "Enable", name: "enable", widget: "boolean", default: true}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Content", name: "content", widget: "text"}
                  - {label: "Privacy Policy Page URL", name: "privacy_policy_page", widget: "string", default: "#"}
                  - {label: "Mailchimp URL", name: "malichipm_url", widget: "string", required: false} # Corrected typo from original config
          - label: "Disqus Comments"
            name: "disqus"
            widget: "object"
            fields:
              - {label: "Enable Disqus", name: "enable", widget: "boolean", default: true}
              - {label: "Disqus Shortname", name: "shortname", widget: "string"}
              # settings object is empty, can be omitted or expanded if needed
      - file: "config/menu.json"
        label: "Navigation Menus"
        name: "menus_config"
        fields:
          - label: "Main Navigation"
            name: "main"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
      - file: "config/social.json"
        label: "Social Media Links"
        name: "social_config"
        fields:
          - {label: "Facebook URL", name: "facebook", widget: "string", required: false}
          - {label: "Stack Overflow URL", name: "stackoverflow", widget: "string", required: false}
          - {label: "Twitter URL", name: "twitter", widget: "string", required: false}
          - {label: "Instagram URL", name: "instagram", widget: "string", required: false}
          - {label: "YouTube URL", name: "youtube", widget: "string", required: false}
          - {label: "LinkedIn URL", name: "linkedin", widget: "string", required: false}
          - {label: "GitHub URL", name: "github", widget: "string", required: false}
          - {label: "GitLab URL", name: "gitlab", widget: "string", required: false}
          - {label: "Discord URL", name: "discord", widget: "string", required: false}
          - {label: "Slack URL", name: "slack", widget: "string", required: false}
          - {label: "Medium URL", name: "medium", widget: "string", required: false}
          - {label: "CodePen URL", name: "codepen", widget: "string", required: false}
          - {label: "Bitbucket URL", name: "bitbucket", widget: "string", required: false}
          - {label: "Dribbble URL", name: "dribbble", widget: "string", required: false}
          - {label: "Behance URL", name: "behance", widget: "string", required: false}
          - {label: "Pinterest URL", name: "pinterest", widget: "string", required: false}
          - {label: "SoundCloud URL", name: "soundcloud", widget: "string", required: false}
          - {label: "Tumblr URL", name: "tumblr", widget: "string", required: false}
          - {label: "Reddit URL", name: "reddit", widget: "string", required: false}
          - {label: "VK URL", name: "vk", widget: "string", required: false}
          - {label: "WhatsApp Number/Link", name: "whatsapp", widget: "string", required: false}
          - {label: "Snapchat Username/Link", name: "snapchat", widget: "string", required: false}
          - {label: "Vimeo URL", name: "vimeo", widget: "string", required: false}
          - {label: "TikTok URL", name: "tiktok", widget: "string", required: false}
          - {label: "Foursquare URL", name: "foursquare", widget: "string", required: false}
          - {label: "RSS Feed URL", name: "rss", widget: "string", required: false}
          - {label: "Email Address", name: "email", widget: "string", required: false}
          - {label: "Phone Number", name: "phone", widget: "string", required: false}
          - {label: "Physical Address", name: "address", widget: "string", required: false}
          - {label: "Skype Username", name: "skype", widget: "string", required: false}
          - {label: "Website URL (other)", name: "website", widget: "string", required: false}
      - file: "config/theme.json"
        label: "Theme Settings"
        name: "theme_config"
        fields:
          - label: "Color Schemes"
            name: "colors"
            widget: "object"
            fields:
              - label: "Default (Light Mode)"
                name: "default"
                widget: "object"
                fields:
                  - label: "Theme Colors"
                    name: "theme_color"
                    widget: "object"
                    fields:
                      - {label: "Primary", name: "primary", widget: "color"}
                      - {label: "Body Background", name: "body", widget: "color"}
                      - {label: "Border", name: "border", widget: "color"}
                      - {label: "Theme Light (e.g., card background)", name: "theme_light", widget: "color"}
                      - {label: "Theme Dark (e.g., dark component background)", name: "theme_dark", widget: "color"}
                  - label: "Text Colors"
                    name: "text_color"
                    widget: "object"
                    fields:
                      - {label: "Default Text", name: "default", widget: "color"}
                      - {label: "Dark Text (Headings)", name: "dark", widget: "color"}
                      - {label: "Light Text (Subdued)", name: "light", widget: "color"}
              - label: "Dark Mode"
                name: "darkmode"
                widget: "object"
                fields:
                  - label: "Theme Colors (Dark Mode)"
                    name: "theme_color"
                    widget: "object"
                    fields:
                      - {label: "Primary", name: "primary", widget: "color"}
                      - {label: "Body Background", name: "body", widget: "color"}
                      - {label: "Border", name: "border", widget: "color"}
                      - {label: "Theme Light (Dark Mode context)", name: "theme_light", widget: "color"}
                      - {label: "Theme Dark (Dark Mode context)", name: "theme_dark", widget: "color"}
                  - label: "Text Colors (Dark Mode)"
                    name: "text_color"
                    widget: "object"
                    fields:
                      - {label: "Default Text", name: "default", widget: "color"}
                      - {label: "Dark Text (Headings)", name: "dark", widget: "color"}
                      - {label: "Light Text (Subdued)", name: "light", widget: "color"}
          - label: "Fonts"
            name: "fonts"
            widget: "object"
            fields:
              - label: "Font Family"
                name: "font_family"
                widget: "object"
                fields:
                  - {label: "Primary Font (e.g., Raleway:wght@400)", name: "primary", widget: "string"}
                  - {label: "Primary Font Type (e.g., sans-serif)", name: "primary_type", widget: "string"}
                  - {label: "Secondary Font (e.g., Merriweather Sans:wght@400;700)", name: "secondary", widget: "string"}
                  - {label: "Secondary Font Type (e.g., sans-serif)", name: "secondary_type", widget: "string"}
              - label: "Font Size"
                name: "font_size"
                widget: "object"
                fields:
                  - {label: "Base Size (px)", name: "base", widget: "string"} # String to match JSON
                  - {label: "Scale Factor (e.g., 1.200)", name: "scale", widget: "string"} # String to match JSON
              - label: "Submenu (Children)"
                name: "children"
                widget: "list"
                required: false
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}
          - label: "Footer Navigation"
            name: "footer"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}